import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import { copyFile, mkdir } from "node:fs/promises";

const distDir = "dist";
const staticAssets = ["manifest.json", "styles.css"];

const copyStaticAssets = {
	name: "copy-static-assets",
	setup(build) {
		build.onEnd(async (result) => {
			if (result.errors.length > 0) return;

			await mkdir(distDir, { recursive: true });
			await Promise.all(
				staticAssets.map((asset) => copyFile(asset, `${distDir}/${asset}`)),
			);
		});
	},
};

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === "production");

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtins],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: `${distDir}/main.js`,
	plugins: [copyStaticAssets],
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}